- README.md
Two places I noticed in the README that were missing a word to correct the grammar.  
Let me know if PRs for documentation nits like this are more noisy or helpful.
Thanks, and good luck on this new experiment!
> Add two missing words to the README

- napi/scripts/napi.js
- napi/src/sys/bindings.h
I changed the `napi` build script to work on Linux platforms in addition to MacOS. I am using the built-in Node.js `os` module to detect the user's system type in order to copy the correct dynamic library file. I also included `<string.h>` as I was having issues with `memcpy` not working on Ubuntu 16.04 LTS.
This address comments in #15
> Linux Build Compatibility 

- README.md
First of all, I'm very enthusiastic about this project. I've read the readme and caught these minor typo's. I also found that the link to "About this guide" in [this chapter](https://github.com/atom/xray/blob/master/README.md#documentation-driven-development) is dead. Where should this lead to?
> Fixed some minor typo's in the readme

- xray_core/Cargo.toml
- xray_core/src/buffer.rs
- xray_core/src/lib.rs
- xray_core/src/notify_cell.rs
- xray_core/src/tree.rs
I'm not sure how useful this pull request actually is but it gets rid of `rand` as a run-time dependency for `xray_core` as `rand` is only used for tests.
> move rand to dev-dependencies

- Cargo.lock
- xray_core/Cargo.toml
- xray_core/src/buffer.rs
- xray_core/src/lib.rs
This pull request contains a few changes that will optimize selection manipulation and cursor movement. I'd recommend reviewing it on a per-commit basis:
* f1361e8 fixes a logic error that was using `Anchor::offset` as an offset into the fragment
* cc7ce29 caches anchor positions until the buffer is edited
* a829f24 wraps `FragmentId`'s vector of identifiers into an `Rc`
* 29b886e uses statically-allocated values for `FragmentId::{min, max}_value`
* 2d6c1b7 caches the mapping between offsets and points until the buffer is edited
I have tested the above optimizations following these steps:
* Edit the buffer 10000 times
* Add 1000 selections
* Start profiling
* Move right
* Stop profiling
| Before …
> Optimize cursor movement and selection manipulation

- xray_electron/lib/render_process/text_editor/text_editor.js
- xray_electron/lib/render_process/view.js
Since these shouldn't trigger re-renders they shouldn't be stored in component state.
> Remove non-render state from component state

- xray_electron/lib/render_process/text_editor/text_plane.js
String refs are legacy API and [likely to be removed][1].
[1]: https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs
> Remove string refs

- xray_core/src/buffer.rs
- xray_core/src/buffer_view.rs
Fixed [warning](https://rust-lang-nursery.github.io/rust-clippy/master/index.html#cast_lossless) about cast lossles from [clippy linter](https://github.com/rust-lang-nursery/rust-clippy).
> Fixed linter warnings about cast lossles

- xray_core/src/buffer_view.rs
- xray_electron/lib/render_process/text_editor/text_editor.js
This pull request adds the following bindings:
- <kbd>shift</kbd> + <kbd>↑</kbd> = Select up
- <kbd>shift</kbd> + <kbd>↓</kbd> = Select down
- <kbd>shift</kbd> + <kbd>←</kbd> = Select left
- <kbd>shift</kbd> + <kbd>→</kbd> = Select right
- <kbd>control</kbd> + <kbd>shift</kbd> + <kbd>↑</kbd> = Add selection above
- <kbd>control</kbd> + <kbd>shift</kbd> + <kbd>↓</kbd> = Add selection below
> Add keybindings for selecting ⬆️⬇️⬅️➡️ & adding selection above/below

- .travis.yml
This pull request slightly changes .travis.yml to prevent it from installing wasm-bindgen over and over again, even when it's already installed in the Travis container.
> Install wasm-bindgen only if it is outdated

- xray_browser/script/server
- xray_core/src/app.rs
- xray_core/src/buffer.rs
- xray_core/src/buffer_view.rs
- xray_core/src/fs.rs
- xray_core/src/rpc/client.rs
- xray_electron/lib/main_process/main.js
- xray_server/src/messages.rs
- xray_server/src/server.rs
- xray_ui/lib/app.js
- xray_ui/lib/text_editor/text_editor.js
- xray_ui/lib/text_editor/text_plane.js
This pull request moves selection ownership down into the buffer so that it can replicated to all workspace participants. We then tweaked the WebGL rendering to assign one of five different colors to selections based on the id of the replica that owns the selection and limit blinking to local cursors only.
> Show selections of all workspace participants

- xray_wasm/script/build
Already 'rust-toolchain' exists, but '+nightly' override toolchain.
We expect nightly-2018-04-27 (from 'rust-toolchain'), but use latest nightly-toolchain.
In my environment(latest nightly installed), problems similar to issue # 72 were occurring.
> Remove '+nightly' option from xray_wasm/scripts/build

- Cargo.toml
- xray_core/benches/bench.rs
- xray_core/src/buffer.rs
- xray_core/src/buffer_view.rs
- xray_core/src/project.rs
- xray_core/src/tree.rs
This pull request takes advantage of the batched nature of multi-cursor editing to improve performance when manipulating the buffer. The following chart shows that, after these changes, editing is ~66% faster on average:
`Buffer::splice_fragments` has now become a little more involved due to trying to reuse as much work as possible from previous edits. I think it's still pretty reasonable though and I have tried to document the various logical steps in the function's body.
Please note that we're still far from being optimal when modifying the buffer. Specifically, based on my measurements, `Cursor::seek_and_slice` becomes slower and slower as more fragments are added to the tree. This seems to be due to the cost of constructing the slices in between ranges but that code path has quite a …
> Splice buffer fragments in batches

- xray_core/src/buffer.rs
- xray_core/src/fs.rs
- xray_core/src/project.rs
- xray_core/src/workspace.rs
- xray_server/src/fs.rs
- xray_ui/lib/workspace.js
This pull request introduces a new `SaveActiveBuffer` command that is dispatched when either pressing <kbd>⌘</kbd><kbd>S</kbd> or <kbd>Ctrl</kbd><kbd>S</kbd>. This new command applies to both local and remote workspaces, which in the latter case issues a save request to the host owning the buffer.
The save routine is carried out on a separate thread thanks to the introduction of `Buffer::snapshot`, which builds a read-only `Send`able clone of the current state of the buffer. Then, after successfully grabbing the file's lock in a background thread, the buffer's tree of visible fragments is traversed, encoded to UTF-8, and written to disk in a streaming fashion. 
At some point in the future we should handle different encodings, as well as coping with file corruption in the presence of an …
> Implement saving feature for buffers

- xray_core/src/buffer.rs
- xray_core/src/buffer_view.rs
- xray_core/src/project.rs
- xray_core/src/rpc/mod.rs
- xray_core/src/workspace.rs
Contrarily to the design I proposed in #84, this pull request takes a step back and moves ownership of `fs::File` down into `Buffer` so that buffers can be pruned more easily from `Project` when nobody is using them anymore.
My original rationale for storing `fs::File` (and a bi-directional mapping between files and buffers) in `Project` was that it felt awkward to clutter the buffer with more responsibilities than it already had. However, the key realization I had today was that `Project` isn't the actual owner of buffers at all. For example, when the last `BufferView` holding a particular buffer goes away, we want that buffer to be forgotten in `Project` as well. The same reasoning applies when all `buffer::rpc::Service` instances are dropped. This clearly indicated that the project …
> Drop buffers that are not being used

- xray_core/src/buffer.rs
- xray_core/src/buffer_view.rs
- xray_core/src/tree.rs
- xray_ui/lib/text_editor/shaders.js
- xray_ui/lib/text_editor/text_editor.js
- xray_ui/lib/text_editor/text_plane.js
This pull request adds the ability to scroll the editor horizontally via the mouse wheel, as well as autoscrolling when the cursor moves. This feature took a couple of days to get implemented because we wanted to find a way of efficiently maintaining the longest line in a given range. This will not only be useful for horizontal scrolling, but will be reused when we will introduce a "display map" to handle folds and soft-wraps. A few highlights related to the proposed changes:
* Each `Insertion` maintains a line index that is specifically designed to efficiently answer the following queries:
* Given a 1d offset, return its 2d position.
* Given a 2d position, return its 1d offset.
* Given an offset range, return the longest row in that range
* The line index is a binary tree represented as …
> Horizontal scrolling

- README.md
- xray_core/src/buffer_view.rs
- xray_ui/lib/text_editor/text_editor.js
- xray_ui/lib/text_editor/text_plane.js
This pull request introduces a gutter into the editor in order to show line numbers.
We simply added an extra pass to the `draw` routine which clears out the rectangle where the gutter will be displayed in and draws line number glyphs on top of it. To achieve this were able to reuse the existing solid and text shaders.
> Show line numbers

- README.md
- xray_core/src/buffer.rs
- xray_core/src/buffer_view.rs
- xray_core/src/movement.rs
- xray_core/src/tree.rs
- xray_ui/lib/app.js
- xray_ui/lib/text_editor/text_editor.js
As the title says, this pull request introduces several word- and line-based cursor movements that are necessary for a basic editing experience. More specifically, this is the list of commands that will be available after this pull request:
* Move To Beginning Of Line
* Move To Beginning Of Word
* Move To Bottom
* Move To End Of Line
* Move To End Of Word
* Move To Top
* Select To Beginning Of Line
* Select To Beginning Of Word
* Select To Bottom
* Select To End Of Line
* Select To End Of Word
* Select To Top
[xray_ui/lib/app.js](https://github.com/atom/xray/compare/word-line-cursor-movements?expand=1#diff-eef0483debc728c2f3f021eba42e84ff) exposes which keymaps these commands are bound to. I have borrowed the mappings from from Atom's macOS keymap file, but creating more bindings to other …
> Introduce word- and line-based cursor movements

- xray_core/src/buffer.rs
This really is a minor refactor but I came a cross it while looking through the code and thought I may as well just submit it.
**What**
Refactor to use [while-let](https://doc.rust-lang.org/rust-by-example/flow_control/while_let.html) syntax instead of a manuell check and assignment
**Why**
- Replaces two `item()` calls with just one
- Gets rid of an `.unwrap()` call
- More idiomatic code
> Refactor to use while-let in buffer.integrate_edit()

- xray_core/src/buffer_view.rs
Attempts to fix #113
Still not perfect: the rust [`char`](https://doc.rust-lang.org/std/char/index.html) returned by `chars()` represent "Unicode Scalar Values" which may not be considered characters 1 to 1:
> It's important to remember that char represents a Unicode Scalar Value, and may not match your idea of what a 'character' is. Iteration over grapheme clusters may be what you actually want.
https://stackoverflow.com/questions/46290655/get-the-string-length-in-characters-in-rust
See this [demo in the rust play ground](http://play.rust-lang.org/?gist=924146e1ba523a96be5417a96e23e58a)
Xray currently displays:
The problem seems to be that the perceived length of a string can't really be determined by the string in isolation. A good example is the `👍🏽` string in the demo: in the editor …
> Improve cursor movement when inserting

- CONTRIBUTING.md
I was getting a blank window, and familiar shortcuts weren't working (I use <kbd>cmd-t</kbd> for something else in Atom). 
This change should unambiguously point out what to expect when launching, and how to open a file.
> Add open file information to CONTRIBUTING

- memo_core/src/btree.rs
- memo_core/src/buffer.rs
- memo_core/src/time.rs
This pull request introduces a new `Tree::filter` method that allows skipping nodes of the B-Tree based on a predicate over each node's summary. This speeds up significantly `Buffer::changes_since`, which now scales with the number of changes that have occurred since the given version.
In the process of implementing this optimization, I also:
* Discovered and fixed a bug in `Buffer::longest_row` (see 1bb91b1 for more details).
* Removed unnecessary comparisons in `Add` and `AddAssign` for `FragmentId` (see c7d56ba).
/cc: @nathansobo
> Speed up Buffer::changes_since by skipping subtrees that haven't changed

- memo_js/.npmignore
- memo_js/package.json
- memo_js/test/tests.js
- memo_js/tsconfig.json
- memo_js/webpack.config.js
This replaces #139 
1. Generate and point to the TypeScript declaration and map file.
1. Build for both web and node.
1. Point the web to its build.
> Fix web and TS building

- memo_js/README.md
- memo_js/src/index.ts
A few more changes to the TS wrapper:
1. Export all the types so consumers can use them.
1. All the exposed fields are conceptually `readonly`. (I _think_! Correct me if I'm wrong!)
1. The file types are actually `Directory | Text` not `Directory | File`, judging by: https://github.com/atom/xray/blob/a7ec528e6c93814d7e1343c72832f58d620cf98c/memo_core/src/work_tree.rs#L127-L130
> Super duper TS

- memo_js/README.md
- memo_js/src/index.ts
1. Fix an example in the README
1. Make another array readonly
1. Give our type aliases more specific type-level semantics.
(3) is nice because it gives type-level semantics to what would otherwise be plain type aliases. For example, even though `FileId` is represented as a `string`, it can't be just any `string`. It should only be a `string` that Memo vends. This lets us encode that in the type system:
```typescript
workTree.remove("my-made-up-id")
^^^ type error
const fileId = workTree.fileIdForPath("my-file.txt")
workTree.remove(fileId)
^^^ just fine
```
but it also gets erased at compile time so it doesn't change runtime semantics.
> Even more types!

- memo_core/src/buffer.rs
- memo_core/src/operation_queue.rs
- memo_core/src/time.rs
- memo_core/src/work_tree.rs
After reloading a web page or performing a similar refresh in other situations, we may need to populate a `WorkTree` from a set of operations that includes operations produced by the same user that is performing the refresh. Previously, we had only tested applying operations produced by other replicas, and this wasn't working.
This PR also makes some adjustments to gracefully handle applying the same operations multiple times to paper over race conditions when subscribing to new operations and fetching existing operations.
This PR adds coverage for both of these scenarios to our randomized tests.
/cc @probablycorey
> Support replay of operations with the same replica id

- memo_js/src/index.ts
- memo_js/src/lib.rs
- memo_js/test/tests.js
Fixes #146
This introduces an extra allocation for each reported entry in memo_js, but it removes an O(depth * log n) scan per entry while also making it more convenient to use for clients. We were already maintaining the path in the cursor, so this change was pretty straightforward.
/cc: @joshaber @nathansobo
> Report also the full path when retrieving entries

- memo_core/src/buffer.rs
- memo_core/src/work_tree.rs
- memo_js/README.md
- memo_js/src/index.ts
This is a naive implementation. Even if the operations cancel each other out, we will still report the buffers as modified.
🍐'd with @nathansobo 
/cc: @probablycorey
> Report text files with edits as modified

- Cargo.lock
- memo_js/Cargo.toml
- memo_js/README.md
- memo_js/src/index.ts
- memo_js/src/lib.rs
- memo_js/test/tests.ts
This pull request skips the extra base64 conversion when returning operations to the JS layer. The returned operations are now returned as `Uint8Array` instances.
/cc: @nathansobo
> Don't encode operations as Base64, but use `Uint8Array`s instead

- memo_core/src/buffer.rs
- memo_core/src/lib.rs
- memo_core/src/serialization/schema.fbs
- memo_core/src/serialization/schema_generated.rs
- memo_core/src/work_tree.rs
- memo_js/src/index.ts
- memo_js/src/lib.rs
- memo_js/test/tests.ts
- memo_js/test/tsconfig.json
Operations are grouped into *epochs*. Each epoch begins at a specific *base commit*. When persisting operations to a database, we want to associate epochs with their base commit so we can determine the *active epoch* for a given branch.
When we receive an operation with an unknown epoch id, we want to create that epoch lazily on the server. Usually, the first operation for a new epoch that we'll receive is the `EpochStart` operation, which includes the head commit's OID. However, we want it to be possible for the server to treat operations as opaque binary, and we don't necessarily want to enforce a strict order on how operations for a given epoch are processed and stored by the server. For these reasons, we're deciding to send the epoch head OID to the server with each operation. This …
> Wrap work tree operations in an envelope that contains the head of the current epoch

- memo_core/src/work_tree.rs
- memo_js/src/index.ts
- memo_js/src/lib.rs
- memo_js/src/support.ts
- memo_js/test/tests.ts
This pull request introduces the following methods:
* `WorkTree.prototype.exists(path)`. This works exactly as its Node counterpart and returns a boolean indicating whether or not a file currently exists at the specified `path`. (cc5ec38)
* `Buffer.prototype.dispose()`. This method is currently just used to un-register the callbacks supplied to `onChange`. In the future, we could actually dispose the buffer and release memory from the WASM layer. (495fe82)
* `Buffer.prototype.getPath()`. If the underlying file that corresponds to the buffer is visible, this method will return a string representing its path. Otherwise, `null` will be returned, and that's an indicator that the file has been deleted. (34a2fca)
/cc: @probablycorey @nathansobo
> Introduce more APIs to work with buffers and paths

- Cargo.lock
- memo_js/Cargo.toml
- memo_js/script/build
- memo_js/src/lib.rs
- memo_js/test/tests.ts
- xray_wasm/Cargo.toml
- xray_wasm/script/build
This pull request takes a pass at the WASM layer and addresses the following issues:
1. When an error occurs in Memo, we return a proper instance of the JavaScript `Error` class instead of a string. (c79cb79)
2. When an error occurs in Javascript, we will catch in Rust and try to report it back to JavaScript only if the error is an instance of `Error`. Otherwise, we will display an error saying that an error occurred but we couldn't understand what it was.
3. Along the way, I upgraded wasm-bindgen from v0.2.25 to v0.2.29, which includes some important bugfixes.
/cc: @probablycorey @jasonrudolph
> Improve error handling

- memo_core/src/buffer.rs
- memo_core/src/epoch.rs
- memo_core/src/operation_queue.rs
- memo_core/src/work_tree.rs
- memo_js/src/index.ts
- memo_js/src/lib.rs
- memo_js/test/tests.ts
This pull request introduces a new method on `Buffer` that allows to retrieve how many operations haven't been applied yet due to a deferral, in an effort to start adding observability into memo's internal state.
We have pretty good confidence that, so long as all messages are delivered, the system will converge. However, higher layers in the stack (e.g., networking, storage, etc.) may cause memo not to see every operation, and so this new simple function will help take operation delivery out of the equation (if the deferred count is zero).
/cc: @joshaber
> Add Buffer.prototype.getDeferredOperationCount

- memo_core/src/buffer.rs
- memo_core/src/epoch.rs
- memo_core/src/lib.rs
- memo_core/src/operation_queue.rs
- memo_core/src/serialization/schema.fbs
- memo_core/src/serialization/schema_generated.rs
- memo_core/src/work_tree.rs
- memo_js/README.md
- memo_js/src/index.ts
- memo_js/src/lib.rs
- memo_js/src/support.ts
- memo_js/test/tests.ts
This pull request introduces new APIs for creating, replacing and removing selections. Examples can be found in the documentation or in tests:
* `Buffer.prototype.addSelectionSet(ranges)`. This method takes an array of ranges representing the initial selections of the set and returns a tuple containing the newly-created set id (that you can use to manipulate the set later on) and an operation that can be broadcasted to other replicas.
* `Buffer.prototype.replaceSelectionSet(setId, ranges)`. This method takes the id of a set that was previously created and an array of ranges to replace the existing ranges in the set. It returns an operation that can be broadcasted to other replicas.
* `Buffer.prototype.removeSelectionSet(setId)`. This method takes the id of a set that was previously …
> Introduce Selections

- memo_core/src/buffer.rs
- memo_core/src/epoch.rs
- memo_core/src/serialization/schema.fbs
- memo_core/src/serialization/schema_generated.rs
- memo_core/src/work_tree.rs
- memo_js/README.md
- memo_js/src/index.ts
- memo_js/src/lib.rs
- memo_js/test/tests.ts
This pull request introduces a first iteration of the location API. Specifically, `WorkTree` will now support the following methods:
* `setActiveLocation(buffer: Buffer | null)`, which can be used to transmit the location of the local replica.
* `getReplicaLocations`, which returns a `Map<ReplicaId, Path>` of the active path for every other replica that we have received a location operation for.
In the future I believe we should enhance this API to also supply a `SelectionSetId`. This is because any given buffer could have an arbitrary number of selections (e.g., when multiple editors are backed by the same buffer), and we want to provide a way of determining which one is the one currently used by each replica.
At some point I think we should do something about all these path-based APIs, …
> Introduce Location API
